title: "Cortez Stewart's Portfolio"
#logo: ![image](https://github.com/user-attachments/assets/312bdeea-5d54-4a78-bf58-5e6d0b0d75f9)

#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
