title: "Cortez Stewart's Portfolio"
#logo:
![image](https://github.com/user-attachments/assets/d064b0da-f393-4089-8be0-bbf1a5efcb63)
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
